### ISSUE TITLE
scope of the package: "kitchen sink syndrome"

### ISSUE THREAD

**Issue by nsajko** [putianyi889/EltypeExtensions.jl#24]
IMO the package suffers from "kitchen sink syndrome": many of the exported functions could rather live in separate packages.

I share the belief that an interface package providing something like `elconvert` is necessary in the ecosystem, however the other functions would ideally be stripped out of this package, because not everyone will need them.

**Comment by putianyi889** [comment]
I understand what you mean. However last time when I tried to register a micropackage, I got rejected and I link their reasons here:
https://github.com/JuliaRegistries/General/pull/102561#issuecomment-1986745775

I'll consider having dedicated packages for the other functions until their implementations become big.

**Comment by nsajko** [comment]
Interesting, thank you for the link. FWIW I disagree with the reasoning given there, and strongly support interface packages.

**Comment by putianyi889** [comment]
> strongly support interface packages

It's not my decision unfortunately. I have to follow the guidance from officials.
